name = "aoc24lean"
version = "0.1.0"
defaultTargets = ["aoc24lean"]

[[lean_lib]]
name = "Aoc24lean"

[[lean_exe]]
name = "aoc24lean"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
