name = "aoc24lean"
version = "0.1.0"
defaultTargets = ["aoc24lean"]

[[lean_lib]]
name = "Aoc24lean"

[[lean_exe]]
name = "day2"
root = "Day2"

[[lean_exe]]
name = "day3"
root = "Day3"

[[lean_exe]]
name = "day4"
root = "Day4"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
